# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38acdde3e224a611eebd45bf64dc6ecaba40ac7d6a9e25d0a4cf0eeae82ac3d247d6f33b8104b075c69c5d2e2f781a813f94cab6800459202bb61519936e7fc4

test:
  secret_key_base: 8e91be51263d9e516403704f30735a4e1b68ed291007e6f9b7ab7f7c0022cbad7907c1d91e14bbca89714c96c032a0bba38440a254513cbaca7ee60fe0928a8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
